In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
import sys
S= range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(S))
print("Size of the whole list in bytes: " , sys.getsizeof(S)*len (S))

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array(42)
print(arr)


42


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)
zeros_arr = np.zeros((2,3))
print(zeros_arr)
zeros_arr_int = np.zeros((3,3), dtype=np.int16)
print("\nArray of zeros with integer elements: \n", zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]

Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
import numpy as np
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3), order='F')
print("\n", newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [11]:
arr1 = np.array([1, 2, 3], dtype=np. float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [12]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1 2 3] int64
After converting:  [1. 2. 3.] float32


In [13]:
arr1 = np.arange(10)
arr2 = np.random. randn (10)
print("array 1\n", arr1, arr1.dtype)
print("Array 2 \n", arr2, arr2.dtype)
new_arr = arr1.astype (arr2.dtype)
arr1.astype(arr2.dtype)
print("New Array \n", new_arr, new_arr.dtype)


array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [ 1.13111652 -2.32329614  1.39815357  0.41440571  0.68760684  0.02236276
  0.76192705  0.0516169  -0.2943963  -0.13250124] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [14]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [15]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
print(a + b)
print(a - b)
print(a + b)
print(a / b)
print(a ** b)


[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 6.  8. 10. 12.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [16]:
import numpy as np
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3), order='F')
print("\n", newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:
import numpy as np
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]])
print(arr)
newarr = arr. reshape (3, 2, 2)
print("\n", newarr)
newarr1 = newarr.reshape(3, -1)
print("\n reshape (3,-1) \n", newarr1)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape (3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [18]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes (arr, 0, 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.multiply(arr1, arr2)
print("Result of element-wise multiplication:")
print(result)
result = np.matmul (arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of element-wise multiplication:
[[ 5 12]
 [21 32]]
Result of matrix multiplication:
[[19 22]
 [43 50]]


In [20]:
result = np.dot (arr1, arr2)
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
[[19 22]
 [43 50]]


In [25]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])

greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2

print("Greater than: \n", greater_than)
print("\nLess than: \n", less_than)
print("\nEqual to: \n", equal_to)

arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])

result1 = np.array_equal(arr3, arr4)
result2 = np.array_equal(arr3, arr5)

print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)


Greater than: 
 [[False  True]
 [False False]]

Less than: 
 [[ True False]
 [False  True]]

Equal to: 
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [27]:
x = np.arange(10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])
print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x[5::-2])
print(x)
x[5] = 2
print("\n After broadcasting1",x)
x[::2] = 100
print("\n After broadcasting2",x)


x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]
[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 6 7 8 9]

 After broadcasting2 [100   1 100   3 100   2 100   7 100   9]


In [28]:
x2 = np.array([[12, 5, 2, 4], [ 7, 6, 8, 8], [ 1, 6, 7, 7]])
print(x2[1] [2])
print(x2 [2, -1])
print(x2[0])


8
7
[12  5  2  4]


In [29]:
import numpy as np
a = np.arange(12). reshape (3,4)
print("a= \n",a)
b = a > 4
print("b= \n", b)
print("a[b]= \n",a[b])
a [b] = 1
print("a= \n",a)


a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]
